jwt:
  secret:
server:
  port:
spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id:
              uri:
              predicates:
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: INFO
    tgb.cryptoexchange: DEBUG